spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fiserv?characterEncoding=UTF-8&useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database: MYSQL
